// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtzWrgJPAp1i2iDxEpf_XkV_WKW9P-zGM',
    appId: '1:852592880758:web:3f3c6e2375089bcdaf4357',
    messagingSenderId: '852592880758',
    projectId: 'multi-store-app2',
    authDomain: 'multi-store-app2.firebaseapp.com',
    storageBucket: 'multi-store-app2.appspot.com',
    measurementId: 'G-R7Q4DTX8R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwIuT3x3PNJ0UevbJV60mJzR304RUrlAc',
    appId: '1:852592880758:android:c9edaeebf040e8b2af4357',
    messagingSenderId: '852592880758',
    projectId: 'multi-store-app2',
    storageBucket: 'multi-store-app2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkdan9-G4-BG-5ZQxxkieVA3F6OcJ1c9Y',
    appId: '1:852592880758:ios:511efabb39e73bfcaf4357',
    messagingSenderId: '852592880758',
    projectId: 'multi-store-app2',
    storageBucket: 'multi-store-app2.appspot.com',
    iosBundleId: 'com.example.multiStoreApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkdan9-G4-BG-5ZQxxkieVA3F6OcJ1c9Y',
    appId: '1:852592880758:ios:801d6a5cdfd4cc49af4357',
    messagingSenderId: '852592880758',
    projectId: 'multi-store-app2',
    storageBucket: 'multi-store-app2.appspot.com',
    iosBundleId: 'com.example.multiStoreApp2.RunnerTests',
  );
}
